In [2]:
!pip3 install pandas

  Using cached pandas-2.3.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 231.9 kB/s eta 0:00:00a 0:00:01
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.3.0-cp312-cp312-macosx_11_0_arm64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 90.0 kB/s eta 0:00:0000:0100:02m
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


list of list

In [3]:
import pandas as pd

l1 = [[11,22,33],[44,55,66],[77,88,99]]
df1 = pd.DataFrame(l1, index=['r1','r2', 'r3'], columns=['c1','c2','c3'])

df1

c1  c2  c3
r1  11  22  33
r2  44  55  66
r3  77  88  99

dict of list

In [4]:
d1 = {'tsla':[200,201,202,203],
      'goog':[500,501,502,503],
      'nvda':[600,601,602,603]}

df2=pd.DataFrame(d1, index = [5,6,7,8])
df2

tsla  goog  nvda
5   200   500   600
6   201   501   601
7   202   502   602
8   203   503   603

list of dict

In [6]:
listd = [
    {'name':'apple','price':300,'sector':'tech'},
    {'name':'ongc','price':500,'sector':'oil'},
    {'name':'artil','price':400,'sector':'fish'}
]
df3=pd.DataFrame(listd, index = [55,66,77])
df3

name  price sector
55  apple    300   tech
66   ongc    500    oil
77  artil    400   fish

numpy array

In [8]:
import numpy as np
import pandas as pd

m1=np.arange(16).reshape(4,4)
print(m1)

df1=pd.DataFrame(m1,index=['r1','r2','r3','r4'],columns=['c1','c2','c3','c4'])
df1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

csv file

In [7]:
import pandas as pd 

df3 = pd.read_csv(r'/Users/olaoluwatunmise/fessopro/11_data_analysis/sp500.csv')
df3

Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30   5.91
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

In [9]:
!pip install lxml

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 2.0 MB/s eta 0:00:0000:0100:010m

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [11]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    102 non-null    object 
 1   Sector  102 non-null    object 
 2   Price   102 non-null    float64
 3   EPS     102 non-null    float64
dtypes: float64(2), object(2)
memory usage: 3.3+ KB


In [12]:
df3.describe()

Price         EPS
count   102.000000  102.000000
mean    150.500686    6.485294
std     240.768463    8.577741
min      12.110000    0.020000
25%      54.335000    2.885000
50%      88.295000    4.405000
75%     151.032500    6.565000
max    1762.230000   74.450000

In [13]:
df3.head()

Name                  Sector   Price    EPS
0            Apple Inc  Information Technology  170.12   9.20
1           Abbvie Inc             Health Care   93.29   5.31
2  Abbott Laboratories             Health Care   55.28   2.41
3        Accenture Plc  Information Technology  145.30   5.91
4         Allergan Plc             Health Care  171.81  15.42

In [14]:
df3.shape


(102, 4)

Single column is called Series
Multiple Column is called DataFrame